### ISSUE TITLE
call back is not invalid?  why is  localhost??

### ISSUE THREAD

**Issue by songbaoqiang** [fh1ch/passport-gitlab2#1]
http://localhost:3000/auth/gitlab/callback?code=c5fefefb733db3c416c8aba10edb23757d0516a6c0d1b6bd8a93af3e64619f6f

**Comment by fh1ch** [comment]
Hi @songbaoqiang 

Thank you for your issue report!

The callback seems about right and matches with the default configuration. Please note that the configuration written in the [README.md](https://github.com/fh1ch/passport-gitlab2#usage) is just an example and might not match with your configuration. Ensure that your webserver is actually listening on **localhost** and adapt the port to match with the one in the callback URL, in this case **3000**.

Most Passport Strategies (including this one) requires setting the callback URL in code. Here an example:

``` js
new GitLabStrategy({
  clientID: 'GITLAB_APP_ID',
  clientSecret: 'GITLAB_APP_SECRET',
  callbackURL: "http://my-awesome-site.com/gitlab/callback" // <- Adapt the value here to your actual configuration
}), ...)
```

This is mostly done by using a mixture between environment variable (for production) and hard-coded default value (for development):

``` js
var canoncialDns = process.env.CANONICAL_DNS || 'http://localhost:8080/';

passport.use(new GitLabStrategy({
  clientID: 'SOME-ID',
  clientSecret: 'SOME_SECRET',
  callbackURL: url.resolve(canoncialDns, 'auth/gitlab/callback')
}, ...);
```

Please let me know if you need more information.

Cheers!

**Comment by fh1ch** [comment]
No response. I'm therefore going to close this issue.
