### ISSUE TITLE
read_user scope undocumented

### ISSUE THREAD

**Issue by almereyda** [fh1ch/passport-gitlab2#3]
From [a discussion](https://github.com/hackmdio/hackmd/issues/301#issuecomment-269363150) we know, that GitLab also does support a `read_user` scope. The documentation in [README.md#how-do-i-change-permissions--scope-when-obtaining-a-user-profile](https://github.com/fh1ch/passport-gitlab2#how-do-i-change-permissions--scope-when-obtaining-a-user-profile) does not reflect this, yet.

**Comment by fh1ch** [comment]
@almereyda thanks for the input!

The scopes for personal tokens were introduces six days ago (see https://about.gitlab.com/2016/12/22/gitlab-8-15-released/#api-changes). I've planned to incorporate this in the next two weeks. 

Cheers!

**Comment by fh1ch** [comment]
Since GitLab 8.15 is no longer supported as part of the security patch-program, I've set the `read_user` scope now to be the default one as part of the `v3.0.0` release (breaking change).

The documentation update was done in a previous commit.
