### ISSUE TITLE
Authorize request each time?

### ISSUE THREAD

**Issue by cimfalab** [fh1ch/passport-gitlab2#6]
Hi,

Each time I am redirected to oauth/authorize it shows up the authorization form, even if I previously approved the authorization.

```
    passport.use(new GitLabStrategy({
        baseURL: xxx,
        clientID: xxx,
        clientSecret: xxx,
        callbackURL: xxx
    }, afterGitLabLoginHandler));

    router.get(yyy, passport.authenticate('gitlab', { scope: ['api'] }));
```

I'm missing something ?

Thank you.

**Comment by fh1ch** [comment]
Hi @cimfalab 

Thanks for your issue report.

I've just tried to reproduce the issue (latest GitLab version as today, latest passport-gitlab2 version), but I wasn't able to reproduce the issue as described by you (I only had to apporve the first time, as expected).

It sound like the authorisation flow is not completely finished in your case and GitLab therefore displays the approval form each time. Do you successfully get a response in your `afterGitLabLoginHandler` and is the application visible in the users GitLab profile?

Cheers

**Comment by cimfalab** [comment]
Thank you for your reply.
I'm using passport-gitlab2 v3.0.0.

I checked 'accessToken' and 'profile' by your advice. But they are logged well in ```function afterGitHubLoginHandler(accessToken, refreshToken, profile, done)```.
The application is also visible in GitLab profile.
But I'm curious what the number besides "Authorized applications" means.
It increments whenever I authorize each time while the 'Authorized At' time is updated.
Can it be a problem?

![gitlab](https://user-images.githubusercontent.com/762690/34381762-ea5cf67c-eb4d-11e7-8cb7-5063a47203ec.png)

Thank you in advance.

**Comment by fh1ch** [comment]
Hmmmm, thats really weird 🤔... I have the same version and also tested successfully against `gitlab.com` in various applications. Do you also get a proper profile (all fields populated)?

Regarding the number beneath `Authorized applications`: this is a counter for all OAuth2 applications you logged-in with your GitLab profile.

**Comment by cimfalab** [comment]
I found something.

My application was registered with 'api' and 'read_user' scopes in GitLab.
In this case, ```passport.authenticate('gitlab', { scope: ['api'] })``` causes authorization form always.

When I update the application only with 'api' scope, it just works as I expected.

So I modifed the code like ```passport.authenticate('gitlab', { scope: ['api', 'read_user'] })```, but GitLab says the requested scope is invalid.

I think 'api' scope will be enough,
but still curious why the scope array is not applicable 🤔

**Comment by fh1ch** [comment]
Awesome, thank you very much for the feedback. This pretty much looks like a GitLab issue to me, as the scope is getting properly passed to the IdP by *passport-gitlab2*. 

By the way: the `read_user` is inherently part of the `api` scope, so only using one is perfectly fine.

**Comment by cimfalab** [comment]
Okay.
It might be a GitLab issue e.g. not handling api%2Cread_user or deprecated(?) 'read_user' scope, ...

Thank you so much for the feedback and detailed explanation.
I developed a service, deepscan.io, integrated with GitHub, and now researching to extend with GitLab.
As of GitLab integration, your project has been helping us a lot!

Thanks again and warm regards

**Comment by fh1ch** [comment]
Always a pleasure, I'm always glad if I can help.

Good luck with the GitLab integration 👍 

By the way: `deepscan.io` looks cool 😎

**Comment by mrsimonemms** [comment]
I know I'm a bit late to the party, but to add multiple scopes you need to set `scopeSeparator` to a single space (ie, `' '`) as [GitLab uses space-separated scopes](https://docs.gitlab.com/api/oauth2/#authorization-code-flow)
